base_model: ../converted-model
datasets:
- path: mhenrichsen/alpaca_2k_test
  type: alpaca
diff_attention: true
sdp_attention: true
gradient_accumulation_steps: 1
learning_rate: 1e-3
max_steps: 1
micro_batch_size: 1
sequence_len: 2048
special_tokens:
  pad_token: <|endoftext|>