# Base Model Configuration
# base_model: google/gemma-3-27b-it #HF Repo of base model, CHANGE TO 14B
base_model: google/gemma-3-4b-it
# base_model: HuggingFaceTB/SmolLM2-135M
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

model_config:
  pad_token_id: 0

special_tokens:
  pad_token: <|endoftext|>

plugins:
  - axolotl.integrations.liger.LigerPlugin
  - axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin #new
liger_rope: true
liger_rms_norm: true
liger_glu_activation: true
liger_layer_norm: true
liger_fused_linear_cross_entropy: false #used to be true
liger_cross_entropy: false #new

val_set_size: 0.0

dataset_prepared_path: /workspace/data/outputs/last_run_prepared
sample_packing: true
pad_to_sequence_len: true

chat_template: gemma3
datasets:
  - path: HuggingFaceH4/ultrachat_200k
    split: train_sft[:5%]
    type: chat_template
    field_messages: messages
    message_property_mappings: 
      role: role
      content: content
eot_tokens:
  - "<end_of_turn>"

# More information about below parameters can be found here: https://docs.axolotl.ai/docs/config.html
logging_steps: 1 #How often to show loss, gradient, etc.
num_epochs: 4
micro_batch_size: 1 # Can tune to desired batch size, but will limit max sequence length due to memory constraints
gradient_accumulation_steps: 1
evals_per_epoch: 1
max_grad_norm: 1.0

optimizer: adamw_torch_fused
sequence_len: 262144
learning_rate: 1e-6
adam_beta1: 0.9              # Standard, well-tested value
adam_beta2: 0.999            # Higher beta2 for more stability
adam_epsilon: 1e-8           # Standard epsilon works well with regular AdamW
warmup_ratio: 0.1
weight_decay: 0.01

bf16: true
fp16: false
tf32: false

# FSDP Configuration
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_offload_params: true
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_transformer_layer_cls_to_wrap: Gemma3DecoderLayer
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_sync_module_states: true
  fsdp_cpu_ram_efficient_loading: true
  fsdp_use_orig_params: true
  fsdp_activation_checkpointing: true

save_strategy: epoch

flash_attention: true # new
# eval_sample_packing: false # new
sequence_parallel_degree: 2
