base_model: NousResearch/Meta-Llama-3.1-8B

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: HuggingFaceFW/fineweb-edu
    name: sample-10BT
    type: completion
dataset_prepared_path: last_run_prepared
val_set_size: 0.01
output_dir: ./outputs/llama31_8b_fft

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

wandb_project: diff-transformer-trials
wandb_entity: axolotl-ai
wandb_watch: all
wandb_name: llama3.1-8b-fft
wandb_log_model: 

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 1
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 2e-5

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 100
evals_per_epoch: 2
eval_table_size:
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: <|end_of_text|>

adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 1e-8
weight_decay: 0.01