# base_model: meta-llama/Llama-3.2-3B
base_model: meta-llama/Llama-3.2-1B
# base_model: Qwen/Qwen2.5-0.5B
# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_glu_activation: true
liger_fused_linear_cross_entropy: true

chat_template: llama3
datasets:
  - path: mlabonne/FineTome-100k
    type: chat_template
    split: train[:20%]
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value

dataset_prepared_path: last_run_prepared
output_dir: ./outputs/out

sequence_len: 1024
sample_packing: true

# adapter: lora
adapter: qlora
lora_model_dir:

lora_r: 16
lora_alpha: 32
# Currently, we don't support dropout with our custom Triton kernels
# lora_dropout: 0.05
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

# lora_mlp_kernel: true
# lora_qkv_kernel: true
# lora_o_kernel: true

load_in_8bit: true
load_in_4bit: false

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 1
optimizer: adamw_torch_fused
# optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 2e-5

bf16: auto
tf32: false

resume_from_checkpoint:
logging_steps: 1
flash_attention: true

warmup_steps: 100
saves_per_epoch: 1
weight_decay: 0.0

fsdp_version: 2
fsdp_config:
  offload_params: false
  auto_wrap_policy: TRANSFORMER_BASED_WRAP
  transformer_layer_cls_to_wrap: LlamaDecoderLayer
  state_dict_type: FULL_STATE_DICT
  sharding_strategy: FULL_SHARD
  reshard_after_forward: true
  activation_checkpointing: false

special_tokens:
  pad_token: <|finetune_right_pad_id|>
  eos_token: <|eot_id|>
