base_model: deepseek-ai/DeepSeek-V2-Lite-Chat
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

# DeepSeek V2 Lite - Testing Config 
# Note: MoE kernels not yet supported for DeepSeek-V2 architecture
# Remove comments below when support is added to the plugin

# plugins:
#   - axolotl.integrations.moe_kernels.plugin.MoeOptimizedPlugin
# 
# moe_kernels: true
# moe_group_size: 64  # Potentially smaller for DeepSeek-V2
# moe_persistent_kernel: true

trust_remote_code: true

load_in_8bit: false
load_in_4bit: false

# Dataset Configuration - Small for testing
datasets:
  - path: mlabonne/FineTome-100k
    type: chat_template
    field_messages: conversations
    message_field_role: from
    message_field_content: value
    split: train[:5%]  # Small subset for testing

dataset_prepared_path: last_run_prepared
output_dir: ./outputs/deepseek-v2-lite-test

# Model Configuration
model_config:
  output_router_logits: true  # Enable for load balancing loss

# Sequence Configuration - Shorter for faster testing
sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

# Training Configuration - Minimal for testing
num_epochs: 1
gradient_accumulation_steps: 1
micro_batch_size: 1

# Optimizer and Learning Rate
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 1e-5  # Lower LR for DeepSeek models
warmup_ratio: 0.05
weight_decay: 0.01
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 1e-8

# Mixed Precision and Performance
bf16: true
fp16: false
tf32: true
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
flash_attention: true

# Logging and Saving - Frequent for testing
logging_steps: 5
save_steps: 50
max_steps: 100  # Stop early for testing

# Special tokens
special_tokens:
  bos_token: "<｜begin▁of▁sentence｜>"
  eos_token: "<｜end▁of▁sentence｜>"
  pad_token: "<｜pad｜>"

# Chat template
chat_template: deepseek_v2

# Additional Configuration
max_grad_norm: 1.0
strict: false

# Debugging options
debug: true

# Wandb Configuration
wandb_project: moe-kernels-test
wandb_entity: axolotl-ai
wandb_watch:
wandb_name: deepseek-v2-lite-test-2048sl
wandb_log_model: