base_model: deepseek-ai/DeepSeek-V3
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

# Optimized MoE Kernels for DeepSeek-V3
# DeepSeek-V3 has 256 experts with 8 activated per token
plugins:
  - axolotl.integrations.moe_kernels.plugin.MoeOptimizedPlugin

moe_kernels: true
moe_group_size: 128  # Optimal for most hardware
moe_persistent_kernel: true  # Enable L2 cache optimization
# Auto-detects deepseek_v3 model type
# Optionally specify explicitly:
# moe_kernel_models:
#   - deepseek_v3

trust_remote_code: true

# QLoRA Configuration for memory-efficient training
load_in_8bit: false
load_in_4bit: true
adapter: qlora
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: false
# Target specific modules for DeepSeek-V3
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

# Dataset Configuration
datasets:
  - path: teknium/OpenHermes-2.5
    type: chat_template
    conversation: deepseek_v3  # DeepSeek v3 chat format

dataset_prepared_path: last_run_prepared
val_set_size: 0.01
output_dir: ./outputs/deepseek-v3-moe-optimized-qlora

# Sequence Configuration
sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true
eval_sample_packing: false

# Training Configuration
num_epochs: 1
gradient_accumulation_steps: 4
micro_batch_size: 1

# Optimizer and Learning Rate
optimizer: paged_adamw_8bit  # Memory-efficient optimizer
lr_scheduler: cosine
learning_rate: 2e-5
warmup_ratio: 0.05
weight_decay: 0.0

# Mixed Precision and Performance
bf16: true
fp16: false
tf32: false
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
flash_attention: true

# Logging and Evaluation
logging_steps: 10
evals_per_epoch: 4
save_strategy: steps
save_steps: 500

# Wandb Configuration (optional)
wandb_project: deepseek-v3-moe-optimized
wandb_entity:
wandb_watch:
wandb_name: deepseek-v3-moe-optimized-qlora
wandb_log_model:

# FSDP Configuration with CPU offloading for large model
# Note: DeepSeek-V3 is 671B parameters, requires substantial resources
# fsdp:
#   - full_shard
#   - auto_wrap
# fsdp_config:
#   fsdp_limit_all_gathers: true
#   fsdp_sync_module_states: true
#   fsdp_offload_params: true  # Enable CPU offloading
#   fsdp_use_orig_params: false
#   fsdp_cpu_ram_efficient_loading: true
#   fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
#   fsdp_transformer_layer_cls_to_wrap: DeepseekV3DecoderLayer
#   fsdp_state_dict_type: SHARDED_STATE_DICT
#   fsdp_sharding_strategy: FULL_SHARD
#   fsdp_backward_prefetch: BACKWARD_PRE

# Special tokens
special_tokens:
  bos_token: "<｜begin▁of▁sentence｜>"
  eos_token: "<｜end▁of▁sentence｜>"

# Chat template
chat_template: deepseek_v3

# Additional Configuration
max_grad_norm: 1.0
strict: false

# Note: DeepSeek-V3 is a 671B parameter model with 37B activated per token.
# The optimized MoE kernels significantly improve training efficiency by:
# - Using contiguous grouped GEMM for expert computations
# - Sorting tokens by expert assignment for better memory coalescence
# - Reducing kernel launch overhead through grouped operations
# - Better GPU utilization through optimized tiling strategies
