base_model: axolotl-ai-co/deepseek-v3-1b-moe-test
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

# Optimized MoE Kernels for DeepSeek-V3 1B - Testing Config (using our initialized model)
# Even more minimal version for rapid testing
plugins:
  - axolotl.integrations.moe_kernels.plugin.MoeOptimizedPlugin

moe_kernels: true
moe_group_size: 128  # Optimal for most hardware
moe_persistent_kernel: true  # Enable L2 cache optimization

trust_remote_code: true

load_in_8bit: false
load_in_4bit: false

# Dataset Configuration - Very small for testing
datasets:
  - path: mlabonne/FineTome-100k
    type: chat_template
    field_messages: conversations
    message_field_role: from
    message_field_content: value
    split: train[:2%]  # Even smaller for quick testing

dataset_prepared_path: last_run_prepared
output_dir: ./outputs/deepseek-v3-1b-test

# Model Configuration
model_config:
  output_router_logits: true  # Enable for load balancing loss

# Sequence Configuration - Shorter for faster testing
sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

# Training Configuration - Very minimal for testing
num_epochs: 1
gradient_accumulation_steps: 1
micro_batch_size: 1

# Optimizer and Learning Rate
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 2e-5
warmup_ratio: 0.05
weight_decay: 0.01
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 1e-8

# Mixed Precision and Performance
bf16: true
fp16: false
tf32: true
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
flash_attention: true

# Logging and Saving - Very frequent for testing
logging_steps: 2
save_steps: 25
max_steps: 50  # Very short for quick testing

# Special tokens
special_tokens:
  bos_token: "<｜begin▁of▁sentence｜>"
  eos_token: "<｜end▁of▁sentence｜>"

# Chat template
chat_template: deepseek_v3

# Additional Configuration
max_grad_norm: 1.0
strict: false

# Debugging options
debug: true

# Wandb Configuration
wandb_project: moe-kernels-test
wandb_entity: axolotl-ai
wandb_watch:
wandb_name: deepseek-v3-1b-test-2048sl
wandb_log_model: