# Initialize a small DeepSeek-V3 style MoE model (~1B parameters)  
# This will create a new model from scratch with random weights

base_model: # Leave empty - we're initializing from config
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
tokenizer_config:
  bos_token: "<｜begin▁of▁sentence｜>"
  eos_token: "<｜end▁of▁sentence｜>"
  pad_token: "<｜pad｜>"

# Enable random initialization from config
random_init_weights: true

# Model architecture configuration for ~1B parameters
# Based on DeepSeek-V3 architecture but scaled down
model_config:
  model_type: deepseek_v3
  vocab_size: 129024         # DeepSeek vocab size
  hidden_size: 1024          # Reduced for 1B parameters
  intermediate_size: 2752    # Reduced (2.69x hidden_size)
  max_position_embeddings: 8192
  
  # Transformer layers  
  num_hidden_layers: 16      # Reduced from more layers
  num_attention_heads: 16    
  num_key_value_heads: 16    # Multi-head attention
  
  # MoE configuration - DeepSeek V3 style but smaller
  n_routed_experts: 32       # Reduced from 256
  n_shared_experts: 2        # Reduced from more shared experts
  num_experts_per_tok: 4     # Reduced from 8
  routed_scaling_factor: 1.0
  aux_loss_alpha: 0.001
  seq_aux: true
  
  # Router and expert configuration
  output_router_logits: true
  router_aux_loss_coef: 0.001
  norm_topk_prob: true
  
  # Attention settings
  attention_dropout: 0.0
  hidden_dropout: 0.0
  rope_theta: 10000.0        # DeepSeek default
  
  # Activation and normalization
  hidden_act: "silu"
  rms_norm_eps: 1e-6
  
  # Initialization
  initializer_range: 0.02

trust_remote_code: true

# Training setup
datasets:
  - path: mlabonne/FineTome-100k
    type: chat_template
    field_messages: conversations
    message_field_role: from
    message_field_content: value
    split: train[:10%]

dataset_prepared_path: last_run_prepared
output_dir: ./outputs/deepseek-v3-1b-moe-init

# Optimized MoE Kernels
plugins:
  - axolotl.integrations.moe_kernels.plugin.MoeOptimizedPlugin

moe_kernels: true
moe_group_size: 128
moe_persistent_kernel: true

# Sequence Configuration
sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

# Training Configuration
num_epochs: 1
gradient_accumulation_steps: 4
micro_batch_size: 2

# Optimizer and Learning Rate  
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 3e-4  # Higher LR for training from scratch
warmup_ratio: 0.1
weight_decay: 0.1
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 1e-8

# Mixed Precision
bf16: true
fp16: false
tf32: true
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
flash_attention: true

# Logging
logging_steps: 10
save_steps: 500

# Additional Configuration
max_grad_norm: 1.0
strict: false
debug: true

# Wandb
wandb_project: moe-init
wandb_entity: axolotl-ai
wandb_name: deepseek-v3-1b-moe-init
wandb_log_model: