# Initialize a small Qwen2-MoE style model (~1B parameters)
# This will create a new model from scratch with random weights

base_model: # Leave empty - we're initializing from config
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
tokenizer_config:
  pad_token: "<|endoftext|>"
  eos_token: "<|im_end|>"
  bos_token: "<|im_start|>"

# Enable random initialization from config
random_init_weights: true

# Model architecture configuration for ~1B parameters
model_config:
  model_type: qwen2_moe
  vocab_size: 151936         # Qwen2 vocab size
  hidden_size: 1024          # Reduced from 2048
  intermediate_size: 2816    # Reduced from 5632 (2.75x hidden_size)
  max_position_embeddings: 8192
  
  # Transformer layers
  num_hidden_layers: 16      # Reduced from 24
  num_attention_heads: 16    # Reduced from 16
  num_key_value_heads: 16    # Same as attention heads (no GQA)
  
  # MoE configuration - smaller but similar structure
  num_experts: 16            # Reduced from 60
  num_experts_per_tok: 2     # Reduced from 4 for efficiency
  moe_intermediate_size: 1024 # Reduced from 1408
  shared_expert_intermediate_size: 2816 # Same as intermediate_size
  decoder_sparse_step: 1     # Every layer has MoE
  
  # Router configuration
  output_router_logits: true
  router_aux_loss_coef: 0.001
  norm_topk_prob: true
  
  # Attention and context
  attention_dropout: 0.0
  hidden_dropout: 0.0
  rope_theta: 1000000.0
  
  # Activation and normalization
  hidden_act: "silu"
  rms_norm_eps: 1e-6
  
  # Initialization
  initializer_range: 0.02

trust_remote_code: true

# Training setup for continued pretraining  
datasets:
  - path: mlabonne/FineTome-100k
    type: chat_template
    field_messages: conversations
    message_field_role: from
    message_field_content: value
    split: train[:10%]

dataset_prepared_path: last_run_prepared
output_dir: ./outputs/qwen2-moe-1b-init

# Optimized MoE Kernels
plugins:
  - axolotl.integrations.moe_kernels.plugin.MoeOptimizedPlugin

moe_kernels: true
moe_group_size: 128
moe_persistent_kernel: true

# Sequence Configuration
sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

# Training Configuration
num_epochs: 1
gradient_accumulation_steps: 4
micro_batch_size: 2

# Optimizer and Learning Rate
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 3e-4  # Higher LR for training from scratch
warmup_ratio: 0.1
weight_decay: 0.1
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 1e-8

# Mixed Precision
bf16: true
fp16: false
tf32: true
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
flash_attention: true

# Logging
logging_steps: 10
save_steps: 500

# Additional Configuration
max_grad_norm: 1.0
strict: false
debug: true

# Wandb
wandb_project: moe-init
wandb_entity: axolotl-ai
wandb_name: qwen2-moe-1b-init
wandb_log_model: