base_model: mistralai/Mixtral-8x22B-Instruct-v0.1
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

# Optimized MoE Kernels for Mixtral 8x22B
# Enables high-performance contiguous grouped GEMM operations
plugins:
  - axolotl.integrations.moe_kernels.plugin.MoeOptimizedPlugin

moe_kernels: true
moe_group_size: 128  # Optimal for most hardware
moe_persistent_kernel: true  # Enable L2 cache optimization

trust_remote_code: true

load_in_8bit: false
load_in_4bit: false

# Dataset Configuration
datasets:
  - path: mlabonne/FineTome-100k
    type: chat_template
    field_messages: conversations
    message_field_role: from
    message_field_content: value
    split: train[:10%]  # Smaller split for large model

dataset_prepared_path: last_run_prepared
output_dir: ./outputs/mixtral-8x22b-moe-optimized

# Model Configuration
model_config:
  output_router_logits: true  # Enable for load balancing loss

# Sequence Configuration
sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

# Training Configuration
num_epochs: 1
gradient_accumulation_steps: 8  # Larger accumulation for big model
micro_batch_size: 1

# Optimizer and Learning Rate
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 1e-5  # Lower LR for large model
warmup_ratio: 0.1
weight_decay: 0.01
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 1e-8

# Mixed Precision and Performance
bf16: true
fp16: false
tf32: true
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
flash_attention: true

# FSDP Configuration for large model
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_limit_all_gathers: true
  fsdp_sync_module_states: true
  fsdp_offload_params: false
  fsdp_use_orig_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: MixtralSparseMoeBlock
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sharding_strategy: FULL_SHARD

# Logging and Saving
logging_steps: 10

# Special tokens
special_tokens:
  pad_token: "<pad>"
  eos_token: "</s>"
  bos_token: "<s>"
  unk_token: "<unk>"

# Chat template
chat_template: chatml

# Additional Configuration
max_grad_norm: 1.0
strict: false

# Debugging options
debug: true

# Wandb Configuration
wandb_project: moe-kernels
wandb_entity: axolotl-ai
wandb_watch:
wandb_name: mixtral-8x22b-moe-kernels-4096sl-pack
wandb_log_model: