base_model: Qwen/Qwen1.5-MoE-A2.7B
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
trust_remote_code: true

datasets:
  - path: mhenrichsen/alpaca_2k_test
    type: alpaca
dataset_prepared_path: last_run_prepared
output_dir: ./outputs/qwen2-moe-qlora-10gb

# Train short seqlen to fit 80GB
sequence_len: 128
sample_packing: false
pad_to_sequence_len: false

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 1
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 0.0002

bf16: auto
tf32: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
resume_from_checkpoint:
logging_steps: 1
flash_attention: true

warmup_ratio: 0.03
saves_per_epoch: 1
weight_decay: 0.0

# Enable router logits if you want aux loss/analysis
model_config:
  output_router_logits: true

special_tokens:

# wandb_project: grouped_mm
# wandb_entity: axolotl-ai
# wandb_watch: all
# wandb_name: grouped
# wandb_log_model:

moe_backend: torch_grouped
