base_model: HuggingFaceTB/SmolLM2-135M
datasets:
  - path: mhenrichsen/alpaca_2k_test
    type: alpaca
  - path: tatsu-lab/alpaca
    type: alpaca

# Streaming config
streaming: true
max_steps: 1000

# Dataset mixing with random strategy (equal probability sampling)
dataset_mixing_strategy: random

gradient_accumulation_steps: 1
learning_rate: 1e-4
micro_batch_size: 1
sequence_len: 4096
special_tokens:
  pad_token: <|endoftext|>
flash_attention: true
sample_packing: false