# This config should fail validation due to mismatched weights length
base_model: HuggingFaceTB/SmolLM2-135M
datasets:
  - path: mhenrichsen/alpaca_2k_test
    type: alpaca
  - path: tatsu-lab/alpaca
    type: alpaca

# Streaming config
streaming: true
max_steps: 1000

# Dataset mixing with INVALID weights (2 datasets, 1 weight - should fail validation)
dataset_mixing_strategy: weighted
mixing_weights: [1.0]  # This should cause a validation error

gradient_accumulation_steps: 1
learning_rate: 1e-4
micro_batch_size: 1
sequence_len: 4096
special_tokens:
  pad_token: <|endoftext|>
flash_attention: true
sample_packing: false