base_model: HuggingFaceTB/SmolLM2-135M
datasets:
  - path: mhenrichsen/alpaca_2k_test
    type: alpaca
  - path: tatsu-lab/alpaca
    type: alpaca

# Streaming config
streaming: true
max_steps: 1000

# Dataset mixing with weighted strategy (70% from first dataset, 30% from second)
dataset_mixing_strategy: weighted
mixing_weights: [0.7, 0.3]

gradient_accumulation_steps: 1
learning_rate: 1e-4
micro_batch_size: 1
sequence_len: 4096
special_tokens:
  pad_token: <|endoftext|>
flash_attention: true
sample_packing: false