# base_model: HuggingFaceTB/SmolLM2-135M
base_model: HuggingFaceTB/SmolLM2-1.7B
# base_model: meta-llama/Llama-3.1-8B
datasets:
  - path: mhenrichsen/alpaca_2k_test
    type: alpaca

gradient_accumulation_steps: 1
learning_rate: 1e-4
val_set_size: 0.1
micro_batch_size: 2
sequence_len: 2048
special_tokens:
  pad_token: <|endoftext|>

# sdp_attention: true
flash_attention: true
sample_packing: true

dataset_prepared_path: ./last_run_prepared
output_dir: /workspace/data/model-out

accelerator_config:
  mixed_precision: fp8  
  fp8_config:
    backend: AO
    recipe_name: tensorwise

# gradient_checkpointing: true

# torch_compile: true

# wandb_project: fp8
# wandb_entity: axolotl-ai
# wandb_watch: all
# wandb_name: smollm2-1.7b-fp8-compile
# wandb_log_model: 
