# base_model: /home/arli/models/Llama-3.3-70B-Instruct
base_model: meta-llama/Llama-3.2-3B-Instruct

train_on_inputs: false
group_by_length: false
load_in_8bit:
load_in_4bit: true
strict: false
sequence_len: 8192
bf16: auto
tf32: false
flash_attention: true

shuffle_merged_datasets: true

#lora_on_cpu: true
#gpu_memory_limit: 21GiB

# datasets:
#   - path: /home/arli/datasets/conversations-rpmax3-llama.jsonl
#     type: input_output

datasets:
  - path: mhenrichsen/alpaca_2k_test
    type: alpaca

dataset_prepared_path: ./lora_last_run_prepared

# Iterations
num_epochs: 1
saves_per_epoch: 1
saves_total_limit: 1

# Evaluation
val_set_size: 0.0025
eval_max_new_tokens: 128
eval_sample_packing: false
evals_per_epoch: 4
eval_table_size:

# LoRA
output_dir: ./qlora_out
adapter: qlora
lora_model_dir:
lora_r: 64
lora_alpha: 64
lora_dropout: 0
lora_target_linear: true
peft_use_rslora: true
save_safetensors: true
#loraplus_lr_ratio: 8

# Sampling
sample_packing: true
pad_to_sequence_len: true

# Batching
gradient_accumulation_steps: 32
micro_batch_size: 1
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: false

# wandb
wandb_mode: # "offline" to save run metadata locally and not sync to the server, "disabled" to turn off wandb
wandb_project:
wandb_entity: # A wandb Team name if using a Team
wandb_watch:
wandb_name:
wandb_run_id: # Set the ID of your wandb run
wandb_log_model: # "checkpoint" to log model to wandb Artifacts every `save_steps` or "end" to log only at the end of training

# Optimizer
optimizer: adamw_torch_fused
lr_scheduler: constant_with_warmup
learning_rate: 1e-5
warmup_ratio: 0.1

# Misc
auto_resume_from_checkpoints: true
logging_steps: 1
weight_decay: 0

plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_layer_norm: true
liger_glu_activation: true
liger_fused_linear_cross_entropy: true

sequence_parallel_degree: 2
heads_k_stride: 1

# # Multi-GPU
# fsdp:
#   - full_shard
#   - auto_wrap
# fsdp_config:
#   fsdp_limit_all_gathers: true
#   fsdp_sync_module_states: true
#   fsdp_offload_params: false
#   fsdp_use_orig_params: false
#   fsdp_cpu_ram_efficient_loading: true
#   fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
#   fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
#   fsdp_state_dict_type: FULL_STATE_DICT
#   fsdp_sharding_strategy: FULL_SHARD
#   fsdp_backward_prefetch: BACKWARD_PRE
#   fsdp_forward_prefetch: false
#   fsdp_activation_checkpointing: true

special_tokens:
  pad_token: "<|endoftext|>"
